BEGIN
    IF (OLD.b_isactive = 1 AND NEW.b_isactive = 0) THEN
		INSERT INTO 
            tkd_log.log_purchaseorder
        SET 
			`v_code` = UUID(),
			`i_code` = OLD.`i_code`,
			`fk_business` = NEW.`fk_business`,
			`fk_user` = NEW.`fk_user_modify`,
            `v_user_name` = (SELECT a.v_name FROM dvw_account.vw_user a WHERE a.i_code = NEW.fk_user_modify),
			`v_activity` = 'DELETE',
            `fk_supplier_old` = OLD.`fk_supplier`,
            `v_receipt_old` = OLD.`v_receipt`,
            `i_price_old` = OLD.`i_price`,
            `i_price_adjusted_old` = OLD.`i_price_adjusted`,
            `i_tax_old` = OLD.`i_tax`,
            `i_tax_adjusted_old` = OLD.`i_tax_adjusted`,
            `i_discount_old` = OLD.`i_discount`,
            `i_discount_adjusted_old` = OLD.`i_discount_adjusted`,
            `i_pricenet_old` = OLD.`i_pricenet`,
            `i_pricenet_adjusted_old` = OLD.`i_pricenet_adjusted`,
            `i_extracharge_old` = OLD.`i_extracharge`,
            `dt_order_old` = OLD.`dt_order`,
            `dt_paid_old` = OLD.`dt_paid`,
            `dt_received_old` = OLD.`dt_received`,
            `b_ispaid_old` = OLD.`b_ispaid`,
            `b_isconfirm_old` = OLD.`b_isconfirm`,
            `v_notes_old` = OLD.`v_notes`
    ELSE
		INSERT INTO 
            tkd_log.log_purchaseorder
        SET
            `v_code` = UUID(),
			`i_code` = OLD.`i_code`,
			`fk_business` = NEW.`fk_business`,
			`fk_user` = NEW.`fk_user_modify`,
            `v_user_name` = (SELECT a.v_name FROM dvw_account.vw_user a WHERE a.i_code = NEW.fk_user_modify),
			`v_activity` = 'UPDATE',
			`fk_supplier_old` = OLD.`fk_supplier`,
            `fk_supplier_new` = NEW.`fk_supplier`,
            `v_receipt_old` = OLD.`v_receipt`,
            `v_receipt_new` = NEW.`v_receipt`,
            `i_price_old` = OLD.`i_price`,
            `i_price_new` = NEW.`i_price`,
            `i_price_adjusted_old` = OLD.`i_price_adjusted`,
            `i_price_adjusted_new` = NEW.`i_price_adjusted`,
            `i_tax_old` = OLD.`i_tax`,
            `i_tax_new` = NEW.`i_tax`,
            `i_tax_adjusted_old` = OLD.`i_tax_adjusted`,
            `i_tax_adjusted_new` = NEW.`i_tax_adjusted`,
            `i_discount_old` = OLD.`i_discount`,
            `i_discount_new` = NEW.`i_discount`,
            `i_discount_adjusted_old` = OLD.`i_discount_adjusted`,
            `i_discount_adjusted_new` = NEW.`i_discount_adjusted`,
            `i_pricenet_old` = OLD.`i_pricenet`,
            `i_pricenet_new` = NEW.`i_pricenet`,
            `i_pricenet_adjusted_old` = OLD.`i_pricenet_adjusted`,
            `i_pricenet_adjusted_new` = NEW.`i_pricenet_adjusted`,
            `i_extracharge_old` = OLD.`i_extracharge`,
            `i_extracharge_new` = NEW.`i_extracharge`,
            `dt_order_old` = OLD.`dt_order`,
            `dt_order_new` = NEW.`dt_order`,
            `dt_paid_old` = OLD.`dt_paid`,
            `dt_paid_new` = NEW.`dt_paid`,
            `dt_received_old` = OLD.`dt_received`,
            `dt_received_new` = NEW.`dt_received`,
            `b_ispaid_old` = OLD.`b_ispaid`,
            `b_ispaid_new` = NEW.`b_ispaid`,
            `b_isconfirm_old` = OLD.`b_isconfirm`,
            `b_isconfirm_new` = NEW.`b_isconfirm`,
            `v_notes_old` = OLD.`v_notes`,
            `v_notes_new` = NEW.`v_notes`
END