DONE

BEGIN
INSERT INTO tkd_log.log_category SET 
    `v_code` = UUID(),
    `i_code` = NEW.`i_code`,
    `fk_business` = NEW.`fk_business`,
    `fk_user` = NEW.`fk_user_modify`,
    `v_user_name` = (SELECT a.v_name FROM dvw_account.vw_user a WHERE a.i_code = NEW.fk_user_modify),
    `v_activity` = 'INSERT',
    `fk_category_new` = NEW.`fk_category`,
    `fk_unit_new` = NEW.`fk_unit`,
    `v_unit_variance_new` = NEW.`v_unit_variance`,
    `fk_promotion_monday_new` = NEW.`fk_promotion_monday`,
    `fk_promotion_tuesday_new` = NEW.`fk_promotion_tuesday`,
    `fk_promotion_wednesday_new` = NEW.`fk_promotion_wednesday`,
    `fk_promotion_thursday_new` = NEW.`fk_promotion_thursday`,
    `fk_promotion_friday_new` = NEW.`fk_promotion_friday`,
    `fk_promotion_saturday_new` = NEW.`fk_promotion_saturday`,
    `fk_promotion_sunday_new` = NEW.`fk_promotion_sunday`,
    `v_code_new` = NEW.`v_code`,
    `v_name_new` = NEW.`v_name`,
    `v_image_new` = NEW.`v_image`,
    `v_image_link_new` = NEW.`v_image_link`,
    `b_distributor_new` = NEW.`b_distributor`,
    `i_price_new` = NEW.`i_price`,
    `i_price2_new` = NEW.`i_price2`,
    `i_price3_new` = NEW.`i_price3`,
    `i_price4_new` = NEW.`i_price4`,
    `i_price5_new` = NEW.`i_price5`,
    `i_point_new` = NEW.`i_point`,
    `i_pricenet_new` = NEW.`i_pricenet`,
    `i_discount_new` = NEW.`i_discount`,
    `i_qty_new` = NEW.`i_qty`,
    `i_qtyalert_new` = NEW.`i_qtyalert`,
    `b_hasstock_new` = NEW.`b_hasstock`,
    `b_stock_merge_new` = NEW.`b_stock_merge`,
    `b_hasformula_new` = NEW.`b_hasformula`,
    `b_loyaltytype_new` = NEW.`b_loyaltytype`,
    `i_loyaltyqtypurchased_new` = NEW.`i_loyaltyqtypurchased`,
    `i_loyaltypointearned_new` = NEW.`i_loyaltypointearned`,
    `b_loyaltymultiply_new` = NEW.`b_loyaltymultiply`,
    `v_notes_new` = NEW.`v_notes`,
    `i_sort_new` = NEW.`i_sort`,
    `i_weight_new` = NEW.`i_weight`,
    `b_commision_new` = NEW.`b_commision`,
    `i_commision_new` = NEW.`i_commision`,
    `b_favorite_not_include_new` = NEW.`b_favorite_not_include`,
    `b_showinplatform_new` = NEW.`b_showinplatform`,
    `b_recommendation_new` = NEW.`b_recommendation`,
    `b_usetrigger_new` = NEW.`b_usetrigger`
END